# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holded < Formula
  desc "CLI tool for Holded API"
  homepage "https://github.com/jaume/holdedcli"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jaumecornado/holdedcli/releases/download/v0.1.0/holdedcli_0.1.0_darwin_amd64.tar.gz"
    sha256 "d5893b62b82cef55047f4f2999ccf9afc5ceaa4bd8df451368193ebb9786bf04"

    def install
      bin.install "holded"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jaumecornado/holdedcli/releases/download/v0.1.0/holdedcli_0.1.0_darwin_arm64.tar.gz"
    sha256 "b51eaa5ae4c17181ec63bac4b9af61f929f3ff26a6c8c855f9e3dc06f8a0bb2c"

    def install
      bin.install "holded"
    end
  end

  test do
    system "#{bin}/holded", "auth", "status"
  end
end
