# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holded < Formula
  desc "CLI tool for Holded API"
  homepage "https://github.com/jaumecornado/holdedcli"
  version "0.2.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jaumecornado/holdedcli/releases/download/v0.2.1/holdedcli_0.2.1_darwin_amd64.tar.gz"
    sha256 "f9f4a71fcf7e0a1cead44b7b810aab69932765b83de5ea44b130ac2f1c11d46c"

    def install
      bin.install "holded"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jaumecornado/holdedcli/releases/download/v0.2.1/holdedcli_0.2.1_darwin_arm64.tar.gz"
    sha256 "1170e48dbe4f9ec41095ad3f91764d7d09f024060d4927b7dda0dedcfda61b1d"

    def install
      bin.install "holded"
    end
  end

  test do
    system "#{bin}/holded", "auth", "status"
  end
end
