# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odooapi < Formula
  desc "CLI tool for Odoo JSON-RPC API"
  homepage "https://github.com/jaumecornado/odooapi-cli"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jaumecornado/odooapi-cli/releases/download/v0.1.0/odooapi-cli_0.1.0_darwin_amd64.tar.gz"
    sha256 "011b6ceba23d2261828dba264f31549a660befcced2a1cb2e5777609ec0a39d0"

    def install
      bin.install "odooapi"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jaumecornado/odooapi-cli/releases/download/v0.1.0/odooapi-cli_0.1.0_darwin_arm64.tar.gz"
    sha256 "8759d1d61fa0e8326730ce5fac2fb8b6c48836f78d737c04d3c3206c9ce6381c"

    def install
      bin.install "odooapi"
    end
  end

  test do
    system "#{bin}/odooapi", "help"
  end
end
